// Code generated by protoc-gen-go.
// source: grpc-kvs.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	grpc-kvs.proto

It has these top-level messages:
	Entry
	GetRequest
	GetResponse
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	RangeRequest
	WatchRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Entry struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto1.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PutRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto1.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto1.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RangeRequest struct {
	StartKey string `protobuf:"bytes,1,opt,name=startKey" json:"startKey,omitempty"`
	MaxKeys  int32  `protobuf:"varint,2,opt,name=maxKeys" json:"maxKeys,omitempty"`
}

func (m *RangeRequest) Reset()                    { *m = RangeRequest{} }
func (m *RangeRequest) String() string            { return proto1.CompactTextString(m) }
func (*RangeRequest) ProtoMessage()               {}
func (*RangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type WatchRequest struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *WatchRequest) Reset()                    { *m = WatchRequest{} }
func (m *WatchRequest) String() string            { return proto1.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()               {}
func (*WatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto1.RegisterType((*Entry)(nil), "proto.Entry")
	proto1.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto1.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto1.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto1.RegisterType((*PutResponse)(nil), "proto.PutResponse")
	proto1.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto1.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto1.RegisterType((*RangeRequest)(nil), "proto.RangeRequest")
	proto1.RegisterType((*WatchRequest)(nil), "proto.WatchRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Kvs service

type KvsClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (Kvs_RangeClient, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Kvs_WatchClient, error)
}

type kvsClient struct {
	cc *grpc.ClientConn
}

func NewKvsClient(cc *grpc.ClientConn) KvsClient {
	return &kvsClient{cc}
}

func (c *kvsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (Kvs_RangeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Kvs_serviceDesc.Streams[0], c.cc, "/proto.Kvs/Range", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvsRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kvs_RangeClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type kvsRangeClient struct {
	grpc.ClientStream
}

func (x *kvsRangeClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kvsClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Kvs_WatchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Kvs_serviceDesc.Streams[1], c.cc, "/proto.Kvs/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvsWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kvs_WatchClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type kvsWatchClient struct {
	grpc.ClientStream
}

func (x *kvsWatchClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Kvs service

type KvsServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Range(*RangeRequest, Kvs_RangeServer) error
	Watch(*WatchRequest, Kvs_WatchServer) error
}

func RegisterKvsServer(s *grpc.Server, srv KvsServer) {
	s.RegisterService(&_Kvs_serviceDesc, srv)
}

func _Kvs_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(KvsServer).Get(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Kvs_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(KvsServer).Put(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Kvs_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(KvsServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Kvs_Range_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvsServer).Range(m, &kvsRangeServer{stream})
}

type Kvs_RangeServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type kvsRangeServer struct {
	grpc.ServerStream
}

func (x *kvsRangeServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

func _Kvs_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvsServer).Watch(m, &kvsWatchServer{stream})
}

type Kvs_WatchServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type kvsWatchServer struct {
	grpc.ServerStream
}

func (x *kvsWatchServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

var _Kvs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Kvs",
	HandlerType: (*KvsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Kvs_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Kvs_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kvs_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Range",
			Handler:       _Kvs_Range_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _Kvs_Watch_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x13, 0xa2, 0x04, 0xb8, 0x7c, 0x50, 0x0c, 0x48, 0x25, 0x42, 0x08, 0x85, 0xa5, 0x0b,
	0x11, 0x1f, 0x03, 0x7f, 0x00, 0xc4, 0xd0, 0x05, 0x75, 0x61, 0x36, 0xd5, 0x51, 0x50, 0x4b, 0x12,
	0x6c, 0x27, 0x6a, 0xff, 0x3c, 0x22, 0xb1, 0x5d, 0xc7, 0x2d, 0x9d, 0x22, 0xdf, 0x3d, 0xe7, 0x37,
	0xcf, 0x19, 0x92, 0x19, 0xab, 0xa6, 0x37, 0xf3, 0x86, 0xe7, 0x15, 0x2b, 0x45, 0x49, 0x7c, 0xf9,
	0xc9, 0xae, 0xc1, 0x7f, 0x2e, 0x04, 0x5b, 0x91, 0x10, 0xbc, 0x39, 0xae, 0x86, 0xee, 0x95, 0x3b,
	0x3a, 0x24, 0x31, 0xf8, 0x0d, 0x5d, 0xd4, 0x38, 0xdc, 0xeb, 0x8e, 0xd9, 0x39, 0xc0, 0x0b, 0x8a,
	0x09, 0xfe, 0xd4, 0xc8, 0xc5, 0x06, 0x99, 0x5d, 0x40, 0x28, 0x5b, 0xbc, 0x2a, 0x0b, 0x8e, 0xfd,
	0xa0, 0xea, 0x8e, 0x00, 0x5e, 0xeb, 0x9d, 0x83, 0xdb, 0x11, 0x31, 0x84, 0x92, 0x54, 0xf7, 0xb4,
	0xd7, 0xc6, 0x4f, 0xb8, 0x40, 0x81, 0x3b, 0x43, 0x07, 0x90, 0xac, 0xbb, 0x9a, 0xbf, 0x83, 0x68,
	0x42, 0x8b, 0x99, 0xc1, 0x07, 0x70, 0xc0, 0x05, 0x65, 0x62, 0x6c, 0xf2, 0x8e, 0x60, 0xff, 0x9b,
	0x2e, 0xdb, 0x33, 0x97, 0x89, 0x7e, 0x76, 0x09, 0xd1, 0x1b, 0x15, 0xd3, 0xcf, 0xf5, 0x48, 0x02,
	0x41, 0xc5, 0xf0, 0xe3, 0x6b, 0xa9, 0x06, 0xee, 0x7f, 0x5d, 0xf0, 0xc6, 0x0d, 0x27, 0x39, 0x78,
	0xad, 0x21, 0x39, 0x56, 0x7b, 0xcb, 0xfb, 0x45, 0xa4, 0xc4, 0x2e, 0xe9, 0x1f, 0x71, 0x3a, 0xbe,
	0x35, 0x31, 0x7c, 0xef, 0x6f, 0x78, 0x5b, 0xd4, 0x21, 0x8f, 0x10, 0x28, 0x19, 0x72, 0xaa, 0xfb,
	0x1b, 0xe6, 0xe9, 0xd9, 0x56, 0xd5, 0x0a, 0xf2, 0xa5, 0x33, 0x39, 0xd1, 0x84, 0xbd, 0x81, 0x34,
	0xd2, 0x45, 0xf9, 0xba, 0x99, 0x73, 0xeb, 0x76, 0xbc, 0x14, 0x36, 0xbc, 0xad, 0xff, 0x9f, 0x7f,
	0x0f, 0x64, 0xe1, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xad, 0xbb, 0xda, 0x7a, 0x3a, 0x02, 0x00,
	0x00,
}
